### ISSUE TITLE
Is this still being worked on?

### ISSUE THREAD

**Issue by wonch002** [Informatica-EIC/REST-API-Samples#34]
I've been writing a Python module to access EDC information and manipulate the data as needed. I discovered this repository recently, and I've got a few questions...

1. Is this officially Informatica, or is this a side project?
2. What kind of efforts are being put into this repository today?
3. Should I consider contributing to this repository?

**Comment by govindduttpullat** [comment]
Hi there,

Your contributions are most welcome.

**Comment by wonch002** [comment]
Thanks! Is this repository owned by Informatica?

**Comment by govindduttpullat** [comment]
Hi there,

The repository is owned by a current Informatica employee.

**Comment by darren-wrigley** [comment]
@wonch002 - if you want to contribute any code examples, we would like to include them.
one way to do that, is to update your fork & submit a pull request,  we can then review and add to the main repository
another way would be to add any files you want to add to this issue & we can test and incorporate

**Comment by wonch002** [comment]
Thank you @darren-wrigley! I have some code I would want to potentially incorporate, but I need to chat with my employer on the legality of me adding my work to the repository. 

I'll get some answers and let you know.

Thanks,
Cameron

**Comment by wonch002** [comment]
I've added a Pull Request. This can be found at https://github.com/Informatica-EIC/REST-API-Samples/pull/35. If/when approved, examples of using this functionality will be added.

**Comment by darren-wrigley** [comment]
pull request was merged
