### ISSUE TITLE
SimilarColumnAssociationReport.java is not showing the Similar Column

### ISSUE THREAD

**Issue by ashishgupta2007** [Informatica-EIC/REST-API-Samples#8]
Hello,

I have executed SimilarColumnAssociationReport.java code in eclipse. Code executed successfully and showing all the columns of the resource. However, it does not display the Similar Columns against the resource column.  Although, I am able to see the similar column in EDC for the same resource columns..

Please help me to resolve this issue.

Thanks!
Ashish Gupta

**Comment by lnt-infa** [comment]
hi Ashish, 

which version of EDC are you on ? 

LNT

**Comment by ashishgupta2007** [comment]
Thanks for the quick response. 

We are using EDC v10.2.1 and with the python code I am able to see the correct report.

Thanks for your help!

Regards,
Ashish Gupta

**Comment by darren-wrigley** [comment]
issue resolved by using v10.2.1 version for extracting column similarity.  there is a difference between the way similarity is represented from 10.2.0 and 10.2.1
